# 用户名
username: ""
# 密码
password: ""
# 医院编号
hoscode: 
# 医生编号
docid: 

# 预约模式：ramdom 随机抢号，order 指定日期
mode: order
# 预约日期，如11-20，不用写年份
date: ""

# 是否开启循环抢号模式
loop: true
# 循环抢号间隔时间，单位毫秒
interval: 1000
# 遇到异常的最大重试次数
max_retry: 3
# 是否开启debug模式
debug: true